name: kubernetes CI

on:
  push:
    branches:
      - main

env:
  APP_NAME: service.doctor.tcm

jobs:
  deploy:
 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }} #ddd
        with:
          args: set image deployment/my-deployment my-container=${{ vars.DOCKERHUB_REGISTRY }}/${{vars.DOCKERHUB_NAMESPACE}}/${{env.APP_NAME}}:${{github.event.release.tag_name}}_${{env.DATETIME}}
