name: Docker Login  

on:  
  push:  
    branches:  
      - main  

jobs:  
  login:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout code  
        uses: actions/checkout@v2  

      - name: Log in to Docker Registry  
        uses: docker/login-action@v2  
        with:  
          registry: crpi-fierbpua1f5su3ae.cn-zhangjiakou.personal.cr.aliyuncs.com  
          username: ${{ secrets.DOCKER_USERNAME }}  
          password: ${{ secrets.DOCKER_PASSWORD }}  

      # 在这里添加其他步骤  
