name: Deploy to ACK

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up KUBECONFIG
      run: |
        echo "KUBECONFIG=$(pwd)/.kube/config" >> $GITHUB_ENV

    - name: Verify connection to Kubernetes cluster
      run: kubectl get nodes
