name: kubernetes CI

on:
  push:
    branches:
      - main

env:
  APP_NAME: service.doctor.tcm

jobs:
  deploy:
 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }} #ddd
      - name: Verify Kubernetes connection
        run: kubectl get pods --all-namespaces
        
