name: kubernetes CI

on:
  push:
    branches:
      - main

env:
  APP_NAME: service.doctor.tcm

jobs:
  deploy:
 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions-hub/kubectl@master
      - name: Set up Kubernetes config
        run: echo '${{ secrets.k8s }}' | base64 --decode > ~/.kube/config

      - name: Verify Kubernetes connection
        run: kubectl get pods --all-namespaces
        
