name: Deploy to ACK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set date as environment variable
      run: echo "DATETIME=$(date +"%Y%m%d")" >> $GITHUB_ENV
    - name: Docker login
      uses: docker/login-action@v1
      with:
        username: 18834576853
        password: q3231423581
        registry: crpi-fierbpua1f5su3ae.cn-zhangjiakou.personal.cr.aliyuncs.com
        logout: true
   
