name: kubernetes CI

on:
  push:
    branches:
      - main

env:
  APP_NAME: service.doctor.tcm

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      # 设置 Kubernetes 配置
      - name: Set up Kubernetes config
        run: |
          mkdir -p ~/.kube
          echo '${{ secrets.k8s }}' | base64 --decode > ~/.kube/config
      

      # 使用解码后的 kubeconfig 文件来运行 kubectl 命令
      - name: Deploy to Kubernetes
        uses: actions-hub/kubectl@master
        with:
          args: "kubectl get pods"
        env:
          KUBECONFIG: ~/.kube/config
