#name: Build and deploy Python app to Docker
#
#on:
#  push:
#    branches:
#      - main
#
#jobs:
#  build-and-deploy:
#    runs-on: ubuntu-latest
#
#    steps:
#    - name: Checkout Repository
#      uses: actions/checkout@v3
#
#    - name: Set up Docker Buildx
#      uses: docker/setup-buildx-action@v2
#
#    - name: Login to Docker Hub
#      uses: docker/login-action@v2
#      with:
#        username: qing161
#        password: Qingfeng,A11
#
#    - name: Build and Push Docker Image
#      uses: docker/build-push-action@v3
#      with:
#        context: .
#        file: ./Dockerfile
#        platforms: linux/amd64
#        tags: qing161/test1030:tagname
#        push: true

name: Build and deploy Python app to Docker

on:
  push:
    branches:
      - main

env:
  ACR_REGISTRY: 'crpi-fierbpua1f5su3ae.cn-zhangjiakou.personal.cr.aliyuncs.com' # 公网地址的前缀部分
  NAMESPACE: 'islilacok'
  REPO_NAME: 'learnner'
  DOCKER_HUB_USERNAME: 'qing161'
  DOCKER_HUB_PASSWORD: 'Qingfeng,A11' # Docker Hub 的密码
  DOCKER_TAG: 'tagname'
  ACR_PASSWORD: 'q3231423581'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKER_HUB_USERNAME }}
        password: ${{ env.DOCKER_HUB_PASSWORD }}

    - name: Login to Alibaba Cloud ACR
      run: |
        echo "${{ env.ACR_PASSWORD }}" | docker login -u aliyun5694155858 --password-stdin ${{ env.ACR_REGISTRY }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        tags: |
          qing161/test1030:${{ env.DOCKER_TAG }} 
          ${{ env.ACR_REGISTRY }}/${{ env.NAMESPACE }}/${{ env.REPO_NAME }}:${{ env.DOCKER_TAG }}
        push: true

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        tags: qing161/test1030:${{ env.DOCKER_TAG }}
        push: true
