#name: Build and deploy Python app to Docker
#
#on:
#  push:
#    branches:
#      - main
#
#jobs:
#  build-and-deploy:
#    runs-on: ubuntu-latest
#
#    steps:
#    - name: Checkout Repository
#      uses: actions/checkout@v3
#
#    - name: Set up Docker Buildx
#      uses: docker/setup-buildx-action@v2
#
#    - name: Login to Docker Hub
#      uses: docker/login-action@v2
#      with:
#        username: qing161
#        password: Qingfeng,A11
#
#    - name: Build and Push Docker Image
#      uses: docker/build-push-action@v3
#      with:
#        context: .
#        file: ./Dockerfile
#        platforms: linux/amd64
#        tags: qing161/test1030:tagname
#        push: true

name: Build and deploy Python app to Docker

on:
  push:
    branches:
      - main

env:
  ACR_REGISTRY: '1954625374569317.dkr.ecr.crpi-fierbpua1f5su3ae.cn-zhangjiakou.personal.cr.aliyuncs.com' # 替换为实际的注册地址
  ACR_IMAGE: 'test1030' # 替换为实际的镜像名称
  DOCKER_HUB_USERNAME: qing161
  DOCKER_HUB_PASSWORD: Qingfeng,A11
  DOCKER_TAG: tagname

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKER_HUB_USERNAME }}
        password: ${{ env.DOCKER_HUB_PASSWORD }}

    - name: Login to Alibaba Cloud ACR
      run: |
        echo ${{ secrets.ACR_PASSWORD }} | docker login -u ${{ env.ACR_REGISTRY }} --password-stdin

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        tags: |
          qing161/${{ env.ACR_IMAGE }}:${{ env.DOCKER_TAG }}
          ${{ env.ACR_REGISTRY }}/${{ env.ACR_IMAGE }}:${{ env.DOCKER_TAG }}
        push: true
